#!/usr/bin/env python3
"""Generate Source/DSP/KemarHrir.h from the MIT KEMAR "compact" HRTF set (horizontal plane).

The MIT KEMAR compact set ships one stereo 44.1 kHz / 16-bit / 128-sample WAV per (elevation, azimuth):
its two channels are the LEFT-ear and RIGHT-ear impulse responses for a source at that azimuth, measured
to the RIGHT of the head (0..180 deg). The head is symmetric, so a source to the LEFT reuses |azimuth|
with the ears swapped. For JASS's left/right PAN we only need the FRONT hemisphere (0..90 deg), so this
tool reads elev0/H0e000a.wav .. H0e090a.wav (19 files, 5 deg steps) and emits a compact float header.

Data license (baked into the generated header): MIT KEMAR HRTF measurements, Bill Gardner & Keith
Martin, MIT Media Lab (1994) — free with no restrictions on use, provided the authors are cited.
  https://sound.media.mit.edu/resources/KEMAR.html

Usage:
    python tools/gen_kemar_hrir.py --input <path-to>/compact/elev0 --output Source/DSP/KemarHrir.h
Download the raw data once from https://sound.media.mit.edu/resources/KEMAR/compact.zip (see tools/README.md).
"""
import argparse, os, struct, wave

STEP_DEG = 5
MAX_AZ = 90          # front hemisphere only (L/R pan maps to +/-90 deg)
EXPECT_SR = 44100
EXPECT_TAPS = 128


def read_hrir(path):
    with wave.open(path, "rb") as w:
        assert w.getnchannels() == 2, f"{path}: expected stereo"
        assert w.getframerate() == EXPECT_SR, f"{path}: expected {EXPECT_SR} Hz"
        assert w.getsampwidth() == 2, f"{path}: expected 16-bit"
        n = w.getnframes()
        raw = w.readframes(n)
    s = struct.unpack("<" + "h" * (n * 2), raw)   # interleaved L,R int16
    left = [s[i] / 32768.0 for i in range(0, len(s), 2)]
    right = [s[i] / 32768.0 for i in range(1, len(s), 2)]
    return left, right


def fmt_row(vals):
    return "        { " + ", ".join(f"{v:.8f}f" for v in vals) + " },"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="path to the KEMAR compact/elev0 directory")
    ap.add_argument("--output", required=True, help="output C++ header path")
    args = ap.parse_args()

    azimuths = list(range(0, MAX_AZ + 1, STEP_DEG))     # 0,5,..,90 -> 19
    left_rows, right_rows, taps = [], [], None
    for az in azimuths:
        path = os.path.join(args.input, f"H0e{az:03d}a.wav")
        l, r = read_hrir(path)
        if taps is None:
            taps = len(l)
        assert len(l) == taps and len(r) == taps, f"{path}: tap-count mismatch"
        left_rows.append(l)
        right_rows.append(r)

    with open(args.output, "w", newline="\n") as f:
        f.write("#pragma once\n")
        f.write("// AUTO-GENERATED by tools/gen_kemar_hrir.py — do not edit by hand. Regenerate to change.\n")
        f.write("//\n")
        f.write("// HRIR data: MIT KEMAR HRTF measurements (horizontal plane, compact set).\n")
        f.write("//   Bill Gardner & Keith Martin, MIT Media Lab (1994).\n")
        f.write("//   \"provided free with no restrictions on use, provided the authors are cited when the\n")
        f.write("//    data is used in any research or commercial application.\"\n")
        f.write("//   https://sound.media.mit.edu/resources/KEMAR.html\n")
        f.write("//\n")
        f.write("// Front hemisphere only (azimuths 0..90 deg, 5 deg steps): a left/right PAN maps to +/-90 deg,\n")
        f.write("// and the symmetric head mirrors the ears for the opposite side. kHrir{Left,Right}[az][tap] is\n")
        f.write("// the left-/right-ear impulse response for a source at that azimuth TO THE RIGHT of the head.\n")
        f.write("namespace KemarHrir\n{\n")
        f.write(f"    inline constexpr int kNumAzimuths   = {len(azimuths)};\n")
        f.write(f"    inline constexpr int kAzimuthStepDeg = {STEP_DEG};\n")
        f.write(f"    inline constexpr int kTaps          = {taps};\n")
        f.write(f"    inline constexpr int kSampleRate    = {EXPECT_SR};\n\n")
        for name, rows in (("kHrirLeft", left_rows), ("kHrirRight", right_rows)):
            f.write(f"    inline constexpr float {name}[kNumAzimuths][kTaps] =\n    {{\n")
            f.write("\n".join(fmt_row(r) for r in rows))
            f.write("\n    };\n\n")
        f.write("}\n")

    print(f"wrote {args.output}: {len(azimuths)} azimuths x {taps} taps (L+R)")


if __name__ == "__main__":
    main()
